// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgW0xtCU7XZVZ4NAeH7Vihlj86UWTOsUw',
    appId: '1:361165861342:web:460b9841fd613f9fd8ed4f',
    messagingSenderId: '361165861342',
    projectId: 'mfys-technology-49193',
    authDomain: 'mfys-technology-49193.firebaseapp.com',
    storageBucket: 'mfys-technology-49193.appspot.com',
    measurementId: 'G-BCF8YL2TRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_0za1xHeJGGGizLy5Xj6uDhuG8JdBLVU',
    appId: '1:361165861342:android:7cbe6d5e6cc1e517d8ed4f',
    messagingSenderId: '361165861342',
    projectId: 'mfys-technology-49193',
    storageBucket: 'mfys-technology-49193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtNlXF3yjB-gR5rARx84xLaJaiUzLhKqc',
    appId: '1:361165861342:ios:c3d8d78f8178c862d8ed4f',
    messagingSenderId: '361165861342',
    projectId: 'mfys-technology-49193',
    storageBucket: 'mfys-technology-49193.appspot.com',
    iosClientId: '361165861342-phlkc964jbo1fo5arsgb0fmdq8f847ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.mfysTechnology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtNlXF3yjB-gR5rARx84xLaJaiUzLhKqc',
    appId: '1:361165861342:ios:5aa1ef91d1433c7ed8ed4f',
    messagingSenderId: '361165861342',
    projectId: 'mfys-technology-49193',
    storageBucket: 'mfys-technology-49193.appspot.com',
    iosClientId: '361165861342-iphnhtt0ptq5ieb3agkf74dl9pekmo50.apps.googleusercontent.com',
    iosBundleId: 'com.example.mfysTechnology.RunnerTests',
  );
}
